use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'FSStockComponets_Example' do
  inhibit_all_warnings!
  
  pod 'FSStockComponets', :path => '../'
  pod 'FSOCCategories/UIButton+FSHitEdgeInsets'
  pod 'FSOCUtils/DeviceUtils'
  pod 'PINCache', '2.3'

  target 'FSStockComponets_Tests' do
    inherit! :search_paths

  end
end
