use_frameworks!

platform :ios, '10.0'

target 'FSStockComponets_Example' do
  inhibit_all_warnings!
  
  pod 'FSStockComponets', :path => '../'
  pod 'PINCache', '2.3'

  target 'FSStockComponets_Tests' do
    inherit! :search_paths

  end
end
